### ISSUE TITLE
Faster Docker build GH actions

### ISSUE THREAD

**Issue by asankov** [asankov/gira#95]
Currently all 3 GH actions that push docker images to Docker Hub, quay.io and GHCR are independently from one another checking out the code, building the images and pushing. We could make a reusable step that builds the images, and 3 different ones that tag them and push to the repository in question. it could look something like:
```yaml
steps:
  build:
    - uses: checkout
    - name: build images
      run: docker build -t {{ matrix.service }} -f Dockerfile.{{ matrix.service }}

  docker_hub:
    depends_on: build

    steps:
       - name: tag
          run: docker tag {{ matrix.service }} asankov/gira-{{ matrix.service }}
       - name: push
          run: docker push asankov/gira-{{ matrix.service }}

# quay.io step

# GHCR step 
```
